monitor=,preferred,auto,1
workspace=DP-1,1

# Variables
$term = kitty

# Startup execs
exec-once=hyprpaper
exec-once=waybar

# Aditional blurs
blurls=waybar
blurls=wofi

input {
    kb_layout=br
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=
    repeat_rate=50
    repeat_delay=250

    follow_mouse=1

    touchpad {
        natural_scroll=yes
    }
}

general {
    sensitivity=1.0 # for mouse cursor
    main_mod=SUPER

    gaps_in=10
    gaps_out=20
    border_size=2
    col.active_border=0xFF9999FF
    col.inactive_border=0x00000000

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

    damage_tracking=full # leave it on full unless you hate your GPU and want to make it suffer
}

decoration {
    rounding=0
    blur=1
    blur_size=3 # minimum 1
    blur_passes=3 # minimum 1, more passes = more resource intensive.
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,6,default
}

dwindle {
    pseudotile=0 # enable pseudotiling on dwindle
}

gestures {
    workspace_swipe=yes
    workspace_swipe_fingers=3
    workspace_swipe_distance=300
    workspace_swipe_min_speed_to_force=0
    workspace_swipe_cancel_ratio=0.2
}

misc {
    disable_hyprland_logo=yes
}

# Window Rules
windowrule=float,^(org.gnome.Nautilus)$
windowrule=move 200 200,^(org.gnome.Nautilus)$

windowrule=float,^(Code)$
windowrule=float,^(qimgv)$
windowrule=float,^(mpv)$

# Fn keys

	# Brightness controll
	bind=,XF86MonBrightnessDown,exec,light -T 0.9
	bind=,XF86MonBrightnessUp,exec,light -T 1.1
	
	# Volume control
	bind=,XF86AudioRaiseVolume,exec,pactl -- set-sink-volume @DEFAULT_SINK@ +1dB
	bind=,XF86AudioLowerVolume,exec,pactl -- set-sink-volume @DEFAULT_SINK@ -1dB
	bind=,XF86AudioMute,exec,pactl -- set-sink-mute @DEFAULT_SINK@ toggle


# Apps Binding

bind=SUPER,RETURN,exec,$term
bind=SUPER,BACKSPACE,killactive,
bind=SUPERSHIFT,Q,exit,
bind=SUPER,E,exec,nautilus
bind=SUPER,V,togglefloating,
bind=SUPER,D,exec,wofi --show drun -o DP-3 -b -i
bind=SUPER,P,pseudo,
bind=SUPER,C,exec,code

bind=SUPERALT,R,exec,shutdown -r 0
bind=SUPERALT,K,exec,shutdown 0

# Focus & Pos handling
bind=SUPER,F,fullscreen,1

bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

bind=SUPER,H,movefocus,l
bind=SUPER,L,movefocus,r
bind=SUPER,K,movefocus,u
bind=SUPER,J,movefocus,d

bind=SUPERSHIFT,left,movewindow,l
bind=SUPERSHIFT,right,movewindow,r
bind=SUPERSHIFT,up,movewindow,u
bind=SUPERSHIFT,down,movewindow,d

bind=SUPERSHIFT,H,movewindow,l
bind=SUPERSHIFT,L,movewindow,r
bind=SUPERSHIFT,K,movewindow,u
bind=SUPERSHIFT,J,movewindow,d

# Screenrecord binding

bind=SUPER,Print,exec,wf-recorder -f ~/Captures/Screenrecording/Recording-$(date +"%H:%M:%S_%d-%m-%Y.mp4")
bind=SUPERSHIFT,Print,exec,killall -s SIGINT wf-recorder
# Workspace binding

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspacesilent,1
bind=ALT,2,movetoworkspacesilent,2
bind=ALT,3,movetoworkspacesilent,3
bind=ALT,4,movetoworkspacesilent,4
bind=ALT,5,movetoworkspacesilent,5
bind=ALT,6,movetoworkspacesilent,6
bind=ALT,7,movetoworkspacesilent,7
bind=ALT,8,movetoworkspacesilent,8
bind=ALT,9,movetoworkspacesilent,9
bind=ALT,0,movetoworkspacesilent,10
