# This is an example Hyprland config file.
# Syntax is the same as in Hypr, but settings might differ.
#
# Refer to the wiki for more information.

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki (basic and advanced configuring)
#

monitor=,preferred,auto,1
workspace=DP-1,1

exec-once=hyprpaper
exec-once=waybar

input {
    kb_file=
    kb_layout=br
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=
    repeat_rate=50
    repeat_delay=250
    follow_mouse=1

    touchpad {
        natural_scroll=yes
    }
}

general {
    sensitivity=1.0 # for mouse cursor
    main_mod=SUPER

    gaps_in=5
    gaps_out=20
    border_size=2
    col.active_border=0xFFA2013F
    col.inactive_border=0x00000000

	layout="master"

    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

    damage_tracking=full # leave it on full unless you hate your GPU and want to make it suffer
}

decoration {
    rounding=6
    blur=1
    blur_size=3 # minimum 1
    blur_passes=3 # minimum 1, more passes = more resource intensive.
    # Your blur "amount" is blur_size * blur_passes, but high blur_size (over around 5-ish) will produce artifacts.
    # if you want heavy blur, you need to up the blur_passes.
    # the more passes, the more you can up the blur_size without noticing artifacts.

}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,6,default
}

dwindle {
	pseudotile=0 # enable pseudotiling on dwindle
}

gestures {
	workspace_swipe=yes
	workspace_swipe_fingers=3
	workspace_swipe_distance=300
	workspace_swipe_min_speed_to_force=0
	workspace_swipe_cancel_ratio=0.2
}

# example window rules
# for windows named/classed as abc and xyz
#windowrule=move 69 420,abc
#windowrule=size 420 69,abc
#windowrule=tile,xyz
#windowrule=float,abc
#windowrule=pseudo,abc
#windowrule=monitor 0,xyz
windowrule=float, ^(org.gnome.Nautilus)$

# example binds
bind=SUPER,return,exec,kitty
bind=SUPER,backspace,killactive,
bind=SUPERSHIFT,Q,exit,
bind=SUPER,E,exec,dolphin
bind=SUPER,V,togglefloating,
bind=SUPER,D,exec,wofi --show drun -o DP-3
bind=SUPER,P,pseudo,
bind=SUPERSHIFT,K,exec,shutdown 0

bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

bind=SUPERSHIFT,left,movewindow,l
bind=SUPERSHIFT,right,movewindow,r
bind=SUPERSHIFT,up,movewindow,u
bind=SUPERSHIFT,down,movewindow,d

bind=SUPER,H,movefocus,l
bind=SUPER,L,movefocus,r
bind=SUPER,K,movefocus,u
bind=SUPER,J,movefocus,d

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspacesilent,1
bind=ALT,2,movetoworkspacesilent,2
bind=ALT,3,movetoworkspacesilent,3
bind=ALT,4,movetoworkspacesilent,4
bind=ALT,5,movetoworkspacesilent,5
bind=ALT,6,movetoworkspacesilent,6
bind=ALT,7,movetoworkspacesilent,7
bind=ALT,8,movetoworkspacesilent,8
bind=ALT,9,movetoworkspacesilent,9
bind=ALT,0,movetoworkspacesilent,10

# Fn keys
# Brightness controll
bind=,XF86MonBrightnessDown,exec,light -T 0.9
bind=,XF86MonBrightnessUp,exec,light -T 1.1
# Volume control
bind=,XF86AudioRaiseVolume,exec,pactl -- set-sink-volume @DEFAULT_SINK@ +1dB
bind=,XF86AudioLowerVolume,exec,pactl -- set-sink-volume @DEFAULT_SINK@ -1dB
bind=,XF86AudioMute,exec,pactl -- set-sink-mute @DEFAULT_SINK@ toggle

misc {
	disable_hyprland_logo=yes

